flowchart LR
  p1[1. Platz] === s1[1. Halbfinalist:in]
  p8[8. Platz] === s1
  p4[4. Platz] === s2[2. Halbfinalist:in]
  p5[5. Platz] === s2
  p3[3. Platz] === s3[3. Halbfinalist:in]
  p6[6. Platz] === s3
  p2[2. Platz] === s4[4. Halbfinalist:in]
  p7[7. Platz] === s4
  s1 === f1[1. Finalist:in]
  s2 === f1
  s3 === f2[2. Finalist:in]
  s4 === f2
  f1 === w[Sieger:in]
  f2 === w
